### ISSUE TITLE
Allow a user to specify a checksum

### ISSUE THREAD

**Issue by Harliff** [chocolatey/chocolatey-ansible#114]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Sometimes we all need to install a chocolatey package for which the original installer package has been updated but the maintainer has not yet updated the checksum in the chocolatey script. Currently, the only way to install such Chocolatey package is to completely ignore the checksum (by seting "ignore_checksums = yes"), but this is not a very secure way. Ignoring the checksum can be dangerous: it makes users vulnerable to attacks such as MITM and "watering hole". 

Can we mitigate it? Yes, we can!

### Describe The Solution. Why is it needed?

The solution is to allow the user of the win_chocolatey module to provide the checksum themselves.

Implementing the use of the provided checksum to check the integrity of the downloaded installer does not seem like a difficult task, because the Chocolatey itself has an options to use a custom checksum.

### Additional Context

Related documentation:
- `--checksum` and `--checksumtype` arguments of the [choco install](https://docs.chocolatey.org/en-us/choco/commands/install) command
- the [Get-ChecksumValid](https://docs.chocolatey.org/en-us/create/functions/get-checksumvalid) function.

**Comment by Harliff** [comment]
The implementation can be quite simple (using only one checksum and fail if it's wrong) and advanced (using the provided checksum as a fallback if the checksum provided by the package maintainer differs from the actual checksum of the download installer).

**Comment by matglas** [comment]
This feature should be really helpful. I have not been able to use any option for arguments to add the checksum and having this as an input ansible properties would be really helpful.

**Comment by vexx32** [comment]
Yeah, this sounds like a great idea 🙂 

> The implementation can be quite simple (using only one checksum and fail if it's wrong) and advanced (using the provided checksum as a fallback if the checksum provided by the package maintainer differs from the actual checksum of the download installer).

@Harliff I think that this would be... _difficult_ to do in any kind of reasonable way short of just re-attempting the install. I'm not sure that's an especially great way for it to work UX-wise.

Rather, I would encourage you to make that feature request into https://github.com/chocolatey/choco itself, and the collection can then use that functionality by proxy.
