### ISSUE TITLE
win_chocolately module does not support removing dependencies

### ISSUE THREAD

**Issue by MrBones757** [chocolatey/chocolatey-ansible#13]
Hello,

When trying to uninstall a package (audacity-lame) i noticed it was leaving the base package (audacity) around.

The module does not appear to have support for the --forcedependencies flag.

I would be happy to submit a PR for this to add this field - just wanted some guidance / options before i cold dropped a PR.

I'm thinking a new parameter called remove_dependencies: true | false

**Comment by vexx32** [comment]
Yeah, this is definitely a gap we should fill in the coverage for sure. `remove_dependencies` sounds like an appropriate name as well, I think.

If you'd like to submit a PR, you're more than welcome to! 🙂

**Comment by MrBones757** [comment]
I have started working on this and we are testing it internally with out workflows / use cases. I will commit and submit a PR once we have validated it.

**Comment by vexx32** [comment]
This was added in #14 and released as part of v1.1.0, closing this as resolved. Thanks for taking care of this!
