### ISSUE TITLE
Remove support for End of Life ansible-core 2.13, 2.14

### ISSUE THREAD

**Issue by Windos** [chocolatey/chocolatey-ansible#140]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

ansible-core 2.13 went [end of life](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) on 2023-11-06 and no longer needs to be included in the test strategy for this collection, nor listed in the support versions of ansible-core.

ansible-core 2.14 also went EOL in May of 2024, so we need to remove that as well.

### Describe The Solution. Why is it needed?

Remove ansible-core 2.13 and 2.14 from the Azure Pipeline test strategy and any README/metadata reference to supporting 2.13 and 2.14.

Additionally, we should include newer currently-supported Ansible versions in our testing matrix.

**Comment by Windos** [comment]
Additional notes: 

- ansible-core 2.14 is going EOL next yesr (2024-05-20)
- ansible-core 2.16 is new and should be added

**Comment by vexx32** [comment]
Noting that 2.14 is now EOL and we have 2.16 and 2.17 to add now (I have updated the issue title and description as well).
