### ISSUE TITLE
Community package requirements: sanity tests

### ISSUE THREAD

**Issue by gotmax23** [chocolatey/chocolatey-ansible#144]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

(Note: This issue was filed in a semi-automated fashion. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `1.5.1` of `chocolatey.chocolatey`, corresponding to the `1.5.1` tag in this repo, fails one or more of the required sanity tests.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.16.1`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

> **💡 NOTE:**
>
> Check the `[explain]` links below for more information about each test and how to fix failures.
> See [Sanity Tests: Ignores](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html) in the dev guide if, after reading the test-specific documentation, you still believe an error is a false positive.

The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible-core/2.16/dev_guide/testing/sanity/validate-modules.html)] failed with 3 errors:

``` text
plugins/modules/win_chocolatey.ps1:0:0: parameter-type-not-in-doc: Argument 'checksum_type' in argument_spec defines type as 'str' but documentation doesn't define type
plugins/modules/win_chocolatey.ps1:0:0: parameter-type-not-in-doc: Argument 'checksum_type64' in argument_spec defines type as 'str' but documentation doesn't define type
plugins/modules/win_chocolatey_facts.ps1:0:0: doc-choices-do-not-match-spec: Argument 'filter' in argument_spec defines choices as ([['all'], ['config'], ['feature'], ['outdated'], ['packages'], ['sources']]) but documentation defines choices as ([])
```

[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst

### What is Expected?

n/a

### How Did You Get This To Happen?

n/a

### System Details

n/a

### Installed Packages

```bash
n/a
```

### Output Log

```bash
n/a
```

**Comment by pauby** [comment]
> If these issues aren't addressed within a reasonable time period,

That's very vague and relative. What is the 'reasonable time period'?

**Comment by gotmax23** [comment]
Thanks for the quick response! I didn't want to put a definite time period on this, as some collections have many errors and other ones, like this one, only have a couple that should be pretty quick to resolve. I'll probably go through the issues and send a reminder if they haven't been updated in, say, a month, but we're not going to remove collections out of the blue unless maintainers are completely nonresponsive after some time has passed.

Also, I would run sanity tests in your CI to make sure no future issues pop up.

**Comment by vexx32** [comment]
I'm pretty sure sanity tests _are_ being run... but I'm not sure why they're not failing the CI, it's something we'll need to dig into. 

We can at least get the outstanding linting issues fixed pretty easily though, I'll take a look at that.
