### ISSUE TITLE
Not able to use chocolatey.chocolatey.win_chocolatey in AWX on CentOS8 - K3S

### ISSUE THREAD

**Issue by narendermann** [chocolatey/chocolatey-ansible#149]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

SSH password: 
BECOME password[defaults to SSH password]: 
ERROR! couldn't resolve module/action 'win_chocolatey'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/windows/install_uninstall_with_chocolatey.yml': line 13, column 6, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  # Install/uninstall with chocolatey
   - name: Ensure 7-Zip is installed through Chocolatey
     ^ here

### What is Expected?

module/action 'win_chocolatey' should work

### How Did You Get This To Happen?

ran the ansible template in AWX tower and got this error.

### System Details

* Operating System: CentOS 8 - Rancher k3s
* Windows PowerShell version: NA
* Chocolatey CLI Version: NA
* Chocolatey Licensed Extension version: No Idea
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
not able to run choco list
```

### Output Log

```bash
SSH password: 
BECOME password[defaults to SSH password]: 
ERROR! couldn't resolve module/action 'win_chocolatey'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/windows/install_uninstall_with_chocolatey.yml': line 13, column 6, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  # Install/uninstall with chocolatey
   - name: Ensure 7-Zip is installed through Chocolatey
     ^ here
```

**Comment by vexx32** [comment]
Are you referencing the module with `win_chocolatey` or the fully qualified name `chocolatey.chocolatey.win_chocolatey`? IIRC some version of Ansible will correctly infer the former, but certain versions may not.

**Comment by narendermann** [comment]
Hello @vexx32  - Thank you for the response on this. I actually tried both. tried chocolatey.chocolatey.win_chocolatey and win_chocolatey both. 

Also tried referencing the chocolatey.chocolatey collection in the playbooks as well.

ALso tried installing chocolatey.chocolatey module in the awx-operator-controller-manager as well with " ansible-galaxy collection install chocolatey.chocolatey" commands. 

Still my AWX is not picking up the chocolatey.chocolatey collection/module.

I do not now wheather its due to the execution environment image or anything else?

**Comment by narendermann** [comment]
ERROR! couldn't resolve module/action 'win_chocolatey'. This often indicates a misspelling, missing collection, or incorrect module path.


The error appears to be in '/runner/project/windows/install_uninstall_with_chocolatey.yml': line 15, column 6, but may

be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
