### ISSUE TITLE
win_chocolatey does not support licensed edition options/switches

### ISSUE THREAD

**Issue by mwtrigg** [chocolatey/chocolatey-ansible#15]
When attempting to install the chocolatey-management-database|service|web packages, I noticed that there was no means of passing a value to the choco --package-parameters-sensitive option.  I then also noticed that the other options avaialable to licensed users are also missing.

Is this an oversight, or intentional?

**Comment by vexx32** [comment]
Up until recently, these modules were part of Ansible's core modules, so while I can't speak for them I would guess that they felt it was better to have the modules mainly support open source Chocolatey features.

We can look at adding some of the licensed edition features if there's a need for it, absolutely. There are some things we'd need to iron out on our end, mainly to do with how we'd handle testing for those features (after all, can't really test those things without a valid Chocolatey license on the Windows agent).

I'm more than happy to take a look at what's missing and add some of the licensed features in as my work schedule permits. If you or anyone else would like to submit PRs for specific features that you have a pressing need for, that's more than welcome as well. 🙂

**Comment by ferventcoder** [comment]
This came up in today's webinar. Something we should definitely look into fixing for the next version of this.

**Comment by ferventcoder** [comment]
So Chocolatey will typically ignore most arguments if it doesn't understand them, that's the default. There is one (`--install-directory`) that it will error on if you use it on an open source edition - b/c so many folks got confused about why that didn't work, we needed to tell them it required a commercial edition. 

I would suggest an option called `additional_arguments` and let those additional things be passed straight to choco. This is similar to what other providers have done for this aspect.

**Comment by vexx32** [comment]
Worth noting that we already have:

- `install_args`
- `override_args`
- `package_params` / `params`

I think it would be best if we made the new option a bit more distinct than just `additional_arguments` as there may be confusion between some of the existing parameters.

Perhaps something like `additional_choco_options`?
