### ISSUE TITLE
Nexus update breaks install.ps1 download

### ISSUE THREAD

**Issue by IanSJones** [chocolatey/chocolatey-ansible#154]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Using Sonatype Nexus Repository ManagerOSS 3.41.1-0 I can place the install.ps1 script under the 'public' directory (c:\programdata\nexus-3.41.1-01\public\install.ps1) and win_chocolatey can download and execute it to install choco.
I have upgraded Nexus to 3.69.0-02 and although the public directory still exists, attempting to https://nexus/install.ps1 gives a 405 - Not Found

I have spoken to Nexus and they suggest I create a raw repository and put the script in there but this will mean I also need win_chocolatey to know what path the repo is.

### What is Expected?

install.ps1 should download

### How Did You Get This To Happen?

I upgraded Nexus from 3.41.1-01 to 3.69.0-02 as Nexus reported a security issue.
Rolling back to the old version removes the issue.

### System Details

* Operating System:  Windows Server 2019 Datacenter
* Windows PowerShell version:  5.1.17763.5122
* Chocolatey CLI Version: Chocolatey v1.1.0
* Chocolatey Licensed Extension version: none
* Chocolatey License type: none
* Terminal/Emulator: mRemoteNG spawned mstsc

### Installed Packages

```bash
PS C:\Users\aqukijo> choco list /l
Chocolatey v1.1.0
chocolatey 1.1.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
Commvault_Agent_UK 11.80.240
crowdstrike 6.37.15103.0
NetWitness 12.1
nexus-repository 3.38.1.01
notepadplusplus 8.4.5
notepadplusplus.install 8.4.5
qualys 5.4.0.10
Temurinjre 18.0.1.1000
```

### Output Log

```bash
TASK [win_chocolatey] **********************************************************
fatal: [tstwdkn6666.qvcuk.local]: FAILED! => {"changed": false, "command": "", "msg": "Failed to download Chocolatey script from 'https://aplwpkn0001/install.ps1'; Exception calling \"DownloadString\" with \"1\" argument(s): \"The remote server returned an error: (404) Not Found.\"", "rc": 0}
```

### Additional Context

We use win_chocolatey in our Ansible playbooks to install software packages but since the Nexus upgrade they have been failing.

**Comment by pauby** [comment]
@IanSJones Under:

> How Did You Get This To Happen?

You need to provide specific details of how to reproduce this issue.

**Comment by IanSJones** [comment]
Sorry Paul.  The output from running a win_chocolatey command to install notepadplusplus using the source https://aplwpkn0001/api/v2/ fails with the output shown in the output log.  The target server does not have choco installed and so your module tried to go to the base url of the source to pull install.ps1, as in https://aplwpkn0001/install.ps1 but because of the Nexus upgrade, the module for a 404 - Not Found response instead of downloading the installer script as usual.

**Comment by pauby** [comment]
Have you [checked the documentation](https://galaxy.ansible.com/ui/repo/published/chocolatey/chocolatey/content/module/win_chocolatey/)?

**Comment by IanSJones** [comment]
Yes, specifically this part:
If neither this parameter nor source is set, the bootstrap script url will be https://community.chocolatey.org/install.ps1
If this parameter is not set, and source is set to a url, the bootstrap script url will be determined from that url instead.

**Comment by pauby** [comment]
What happens if you set it to the URL of the install script?

**Comment by IanSJones** [comment]
You mean:
  - win_chocolatey:
      name: notepadplusplus
      version: '6.6'
      source: https://aplwpkn0001/install.ps1
      validate_certs: false
      
  I get the same error:
  fatal: [tstwdkn6666.qvcuk.local]: FAILED! => {"changed": false, "command": "", "msg": "Failed to download Chocolatey script from 'https://aplwpkn0001/install.ps1'; Exception calling \"DownloadString\" with \"1\" argument(s): \"The remote server returned an error: (404) Not Found.\"", "rc": 0}
  
This is because Nexus is no longer scanning the web page root.  "The bootstrap script url" is incorrect using the later version of Nexus.

**Comment by pauby** [comment]
So if you click `https://aplwpkn0001/install.ps1` you get the install script? That's the actual URL?

**Comment by IanSJones** [comment]
yes it is and it automatically downloads and is executed by win_chocolatey.

**Comment by pauby** [comment]
Why are you using `source` and not `bootstrap_url`?

**Comment by IanSJones** [comment]
Except in the latest Nexus I cannot put the script under the root.  So I am guessing that win_chocolatey needs to be told where to pull the script from.
If bootstrap_url is how I tell win_chocolatey where to go to pull the installer then I will edit all my source to add this in.
I was implying that you could make the bootstrap_url default to something different, now that I can't put it in your current default location, that being the root of the source.

**Comment by pauby** [comment]
> So I am guessing that win_chocolatey needs to be told where to pull the script from.

It does. That's where `bootstrap_url` is used and why I pointed to the docs.

> I was implying that you could make the bootstrap_url default to something different, now that I can't put it in your current default location, that being the root of the source.

The default is to use the root of the source. If you want to do something different, use `bootstrap_url`.

**Comment by IanSJones** [comment]
use bootstrap_url if nexus cannot make the script available under root
