### ISSUE TITLE
win_chocolatey: ChocolateyInstall.ps1 from Internal Repositories fails (Sonatype Nexus)

### ISSUE THREAD

**Issue by adilio** [chocolatey/chocolatey-ansible#18]
* Ansible Version: 2.9
* Chocolatey Module Version: ??

Myself and @steviecoaster have just worked through this with a customer setting up C4B and an organizational installation hosted on Sonatype Nexus. The "raw" repository hosting the offline install script for Chocolatey itself is at a URL similar to:
http://localhost:8081/repository/choco-install/install.ps1

The `win_chocolatey` module uses the Chocolatey (Simple) Server approach of only looking in the root URL for an `install.ps1` script. This is not the pattern in other repository management applications like Sonatype Nexus or JFrog Artifactory.

We need to build some conditional logic into this statement, to handle these additional use cases for our C4B customers:

https://github.com/chocolatey/chocolatey-ansible/blob/a5b9a108ed9bef186da4d5c029d73cb28da07ce7/chocolatey/plugins/modules/win_chocolatey.ps1#L250-L263

**Comment by jborean93** [comment]
If someone had a task

```
- win_chocolatey:
    name: chocolatey
    state: present
    source: http://script/url/from/generic/tab/ChocolateyInstall.ps1
```

Then it should be using that URL to get that script and install Chocolatey. The workflow of [bootstrapping code](https://github.com/chocolatey/chocolatey-ansible/blob/a5b9a108ed9bef186da4d5c029d73cb28da07ce7/chocolatey/plugins/modules/win_chocolatey.ps1#L250-L274) followed this format

* If `source` is not defined use `https://chocolatey.org/install.ps1`
* If `source` ends with `.ps1` then use that directly to download the script and install
* Else get the scheme and authority and append `/install.ps1` and use that to bootstrap Chocolatey - this is meant to work with Chocolatey simple server

So the scenario that was given by @adilio should work right now without any changes.

**Comment by ferventcoder** [comment]
Just for more clarity, this ends failing on 

https://github.com/chocolatey/chocolatey-ansible/blob/a5b9a108ed9bef186da4d5c029d73cb28da07ce7/chocolatey/plugins/modules/win_chocolatey.ps1#L310-L312.

**Comment by ferventcoder** [comment]
We are watching this miss the section on installation at https://github.com/chocolatey/chocolatey-ansible/blob/a5b9a108ed9bef186da4d5c029d73cb28da07ce7/chocolatey/plugins/modules/win_chocolatey.ps1#L281-L291

Check mode is not on, but it never runs this section. It's kind of perplexing on our end, hopefully we'll have more details on this soon.

**Comment by jborean93** [comment]
This is definitely a weird one based on the output shared we can see that `"changed": true` is set but no warning message is shown on the output so the `Run-Command` block isn't running at all. Based on the verbose output there's no indication that check mode has been set and even if it was it would be showing as skipped with https://github.com/ansible/ansible/blob/v2.9.9/lib/ansible/modules/windows/win_chocolatey.ps1#L295-L299.

You can set `ANSIBLE_KEEP_REMOTE_FILES=true` as an env var and Ansible will place the powershell payload in the user's temp dir (folder can be configured) that is run for a module on the file system and will not delete the file when it's finished. You can then inspect this payload to see the exact options that Ansible sends to the module. Keep in mind this may contain sensitive data so it should only ever be set for debugging purposes.

**Comment by adilio** [comment]
I have since tested this install method, @vexx32, and can confirm it now works as expected. I'll go ahead and close this issue.

Appreciate your efforts!
