### ISSUE TITLE
Need a way to attach versioning to module

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-ansible#19]
We were in looking for what version of the Chocolatey module we were on. Unfortunately there isn't an easy way to see that (unless I missed something). Now that the module was separated from Ansible versions, it would have a version of its own.

**Comment by vexx32** [comment]
What do you mean? The module version is equivalent to the collection version, which is available from the manifest yml in the collection package.

Ansible added `ansible-galaxy collection list` in Februrary -- https://github.com/ansible/ansible/pull/65022 -- so it should be available through that command, I think?

**Comment by ferventcoder** [comment]
I mean there is nothing here to tell us what version folks are on. We can't sit with a customer and go "what version of the module do you have" (or can we?).

**Comment by vexx32** [comment]
Yeah, `ansible-galaxy` should be able to list which version of the collection they're using, assuming they have that recently up to date. That said.. their documentation isn't clear on where exactly it's displayed: https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#collection-versions

But at the very least `ansible-galaxy collection list` should show the version they're using.

**Comment by jborean93** [comment]
Yep `ansible-galaxy collection list` is what you want here. You can even specify a specific collection if you only care about that version.

```bash
(ansible-py37) jborean:~$ ansible-galaxy collection list

# /Users/jborean/dev/ansible_collections
Collection            Version     
--------------------- ------------
ansible.windows       0.0.1-beta.3
chocolatey.chocolatey 1.0.2       
community.crypto      0.1.0       
community.general     0.1.1       
community.windows     0.0.1       
(ansible-py37) jborean:~$ ansible-galaxy collection list chocolatey.chocolatey

# /Users/jborean/dev/ansible_collections
Collection            Version
--------------------- -------
chocolatey.chocolatey 1.0.2 
```

If a user does not have Ansible 2.10 installed (which is when list was added) you can manually check the `MANIFEST.json` where the collection is installed

```bash
(ansible-py37) jborean:~$ cat ~/dev/ansible_collections/chocolatey/chocolatey/MANIFEST.json 
{
 "collection_info": {
  "namespace": "chocolatey",
  "name": "chocolatey",
  "version": "1.0.2",
  "authors": [
   "Joel Francis (@vexx32)",
   "Adil Leghari (@adilio)",
   "Trond Hindenes (@trondhindenes)",
   "Peter Mounce (@petemounce)",
   "Pepe Barbe (@elventear)",
   "Adam Keech (@smadam813)",
   "Pierre Templier (@ptemplier)",
   "Jordan Borean (@jborean93)"
  ],
  "readme": "README.md",
  "tags": [
   "chocolatey",
   "windows",
   "packaging",
   "package_management"
  ],
  "description": "Manage packages using Chocolatey.",
  "license": [],
  "license_file": "LICENSE",
  "dependencies": {},
  "repository": "https://github.com/chocolatey/chocolatey-ansible",
  "documentation": "https://github.com/chocolatey/chocolatey-ansible",
  "homepage": "https://github.com/chocolatey/chocolatey-ansible",
  "issues": "https://github.com/chocolatey/chocolatey-ansible/issues"
 },
 "file_manifest_file": {
  "name": "FILES.json",
  "ftype": "file",
  "chksum_type": "sha256",
  "chksum_sha256": "8b4d0bfd37aced864b2ce4dc0a9d074ae4d5a8aae48c655c91f278a40c674732",
  "format": 1
 },
 "format": 1
}
```

**Comment by vexx32** [comment]
Appreciate the confirmation! 💖 

I'll close this for now, then.

**Comment by ferventcoder** [comment]
Thanks folks!
