### ISSUE TITLE
Choco upgrade with --allow-multiple tries to remove old installations

### ISSUE THREAD

**Issue by subhiandrews** [chocolatey/chocolatey-ansible#24]
We use ansible playbooks for  doing choco installs. We use allow_multiple because we want to be able to install a new version while the old one is still running. New version will be used only on the next restart. We also want to be able to install an older version than latest. So set 'state' to 'downgrade' in playbooks. This causes Ansible to create command with following set of parameters

C:\\ProgramData\\chocolatey\\bin\\choco.exe upgrade PFDeltaServiceRelease --fail-on-unfound --yes --no-progress --limit-output --allow-downgrade --allow-empty-checksums --allow-multiple --source https://nexusrepository/ --timeout 2700 --version 7.5.2502.2

We see following error while doing such multiple installs

`
stdout": "Upgrading the following packages:\r\nPFDeltaServiceRelease\r\nBy upgrading you accept licenses for the packages.\r\nThis is try 1/3. Retrying after 300 milliseconds.\r\n Error converted to warning:\r\n (5) Access is denied: [\\\\?\\C:\\ProgramData\\chocolatey\\lib-bkp\\pfdeltaservicerelease.7.8.2664.1]\r\nThis is try 2/3. Retrying after 400 milliseconds.\r\n Error converted to warning:\r\n (5) Access is denied: [\\\\?\\C:\\ProgramData\\chocolatey\\lib-bkp\\pfdeltaservicerelease.7.8.2664.1]\r\nMaximum tries of 3 reached. Throwing error.\r\nThis is try 1/3. Retrying after 300 milliseconds.\r\n Error converted to warning:\r\n (32) The process cannot access the file because it is being used by another process: [\\\\?\\C:\\ProgramData\\chocolatey\\lib\\pfdeltaservicerelease.7.8.2664.1\\tools]\r\nThis is try 2/3. Retrying after 400 milliseconds.\r\n Error converted to warning:\r\n (32) The process cannot access the file because it is being used by another process: [\\\\?\\C:\\ProgramData\\chocolatey\\lib\\pfdeltaservicerelease.7.8.2664.1\\tools]\r\nMaximum tries of 3 reached. Throwing error.\r\nError during backup (move phase):\r\n (32) The process cannot access the file because it is being used by another process: [\\\\?\\C:\\ProgramData\\chocolatey\\lib\\pfdeltaservicerelease.7.8.2664.1\\tools]\r\nThere was an error accessing files. This could mean there is a \r\n process locking the folder or files. Please make sure nothing is \r\n running that would lock the files or folders in this directory prior \r\n to upgrade. If the package fails to upgrade, this is likely the cause.\r\n\r\npfdeltaservicerelease v7.5.2502.2\r\npfdeltaservicerelease package files upgrade completed. Performing other installation steps.\r\nDownloading PFDeltaService \r\n from 'http://nexus.parallaxfund.com:8081/repository/pf-rawzip-internal/PFDeltaService.7.5.2502.2.zip'\r\n\r\nDownload of PFDeltaService.7.5.2502.2.zip (26.07 MB) completed.\r\nExtracting C:\\Users\\servicebamboo\\AppData\\Local\\Temp\\chocolatey\\pfdeltaservicerelease\\7.5.2502.2\\PFDeltaService.7.5.2502.2.zip to C:\\ProgramData\\chocolatey\\lib\\pfdeltaservicerelease.7.5.2502.2\\tools...\r\nERROR: Can not delete output file : Access is denied. : C:\\ProgramData\\chocolatey\\lib\\pfdeltaservicerelease.7.5.2502.2\\tools\\Activ.ContentGatewayApi.dll\r\nERROR: Can not delete output file : Access is denied. :
`

**Comment by vexx32** [comment]
Apologies for the delay in response; I've had a look through, and I'm not entirely sure this behaviour is unexpected. `upgrade` as a command would by its nature look for an existing version to modify if there is one.

Does this work if you use a more direct `state: present` to do the install?

**Comment by pauby** [comment]
This appears to be expected behaviour and there has been no response for some time. I'm going to go ahead and close this now but we can always reopen it later.
