### ISSUE TITLE
--install-directory not working?

### ISSUE THREAD

**Issue by mccw** [chocolatey/chocolatey-ansible#26]
I'm trying to change the installation directory for dotCover CLI and it just isn't being recognized. I've tried
package_params: --install-directory=c:\dotCover
install_args: --install-directory=c:\dotCover
override_args: --install-directory=c:\dotCover
params: --install-directory=c:\dotCover

**Comment by mccw** [comment]
Never mind. I tried from the command line and received the following message:

It appears you are attempting to use options that may be only available in licensed versions of Chocolatey ('--install-directory=c:\dotcover'). There may be ways in the open source edition to achieve what you are looking to do. Please remove the argument and consult the documentation.

**Comment by vexx32** [comment]
Aye, that is a prerequisite for that feature. Was this module not surfacing that response at all?

**Comment by mccw** [comment]
It was not. The run was showing completed with no error or warning.

**Comment by vexx32** [comment]
Attempting this locally gives me an exit code of `1` from Chocolatey. I'm not sure how/why this would get missed by the Ansible module, it generally interprets that exit code as a failure and should report it as such, along with the error message from Chocolatey itself concerning the usage of the argument in an unlicensed version.

I'm going to close this for now, if folks run across this in future feel free to ping me to reopen and we'll see if there's more we need do here to make this behaviour more clear. 🙂
