### ISSUE TITLE
Choco install from NFS source

### ISSUE THREAD

**Issue by andrescolodrero** [chocolatey/chocolatey-ansible#33]
HI,
for internal packages we are using:
choco install mypackage --source=//servername/choco/mypackage

But from ansible, i got this error

 - NuGet.CommandLine - NuGet.CommandLine not installed. The package was not found with the source(s) listed.",
        " Source(s): '\\\\servername\\choco\'",

i tried as config:
//servername/choco/mypackage
\\servername\choco\mypackage

only for for https source?

**Comment by pauby** [comment]
What is the task you are using and what is the verbose output from Ansible?

**Comment by andrescolodrero** [comment]
So the source is: //repository/Microsoft/BoxStarterSetup
and it works from the windows machine,

here the tasks
`- name: Add artifactory netshare internal source
  win_chocolatey_source:
    name: BoxStarter
    state: absent
    priority: 10
    source: //repository/Microsoft/BoxStarterSetup
- name: install git.install
  win_chocolatey:
    name: Nuget.CommandLine
    source: BoxStarter

`


and here the log

`{
    "changed": false,
    "invocation": {
        "module_args": {
            "ignore_checksums": false,
            "source_username": null,
            "architecture": "default",
            "allow_prerelease": false,
            "install_args": null,
            "allow_multiple": false,
            "source_password": null,
            "source": "//repository/Microsoft/BoxStarterSetup",
            "version": null,
            "state": "latest",
            "ignore_dependencies": false,
            "proxy_username": null,
            "pinned": null,
            "force": false,
            "skip_scripts": false,
            "allow_empty_checksums": false,
            "timeout": 2700,
            "proxy_password": null,
            "proxy_url": null,
            "package_params": null,
            "validate_certs": true,
            "name": [
                "NuGet.CommandLine"
            ]
        }
    },
    "rc": 1,
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe install NuGet.CommandLine --fail-on-unfound --yes --no-progress --limit-output --source //repository/Microsoft/BoxStarterSetup --timeout 2700",
    "stdout": "Installing the following packages:\r\nNuGet.CommandLine\r\nBy installing you accept licenses for the packages.\r\nNuGet.CommandLine not installed. The package was not found with the source(s) listed.\r\n Source(s): '//repository/Microsoft/BoxStarterSetup'\r\n NOTE: When you specify explicit sources, it overrides default sources.\r\nIf the package version is a prerelease and you didn't specify `--pre`,\r\n the package may not be found.\r\nPlease see https://chocolatey.org/docs/troubleshooting for more \r\n assistance.\r\n\r\nChocolatey installed 0/1 packages. 1 packages failed.\r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\n\r\nFailures\r\n - NuGet.CommandLine - NuGet.CommandLine not installed. The package was not found with the source(s) listed.\r\n Source(s): '//repository/Microsoft/BoxStarterSetup'\r\n NOTE: When you specify explicit sources, it overrides default sources.\r\nIf the package version is a prerelease and you didn't specify `--pre`,\r\n the package may not be found.\r\nPlease see https://chocolatey.org/docs/troubleshooting for more \r\n assistance.\r\n",
    "stderr": "",
    "msg": "Error installing package(s) 'NuGet.CommandLine'",
    "stdout_lines": [
        "Installing the following packages:",
        "NuGet.CommandLine",
        "By installing you accept licenses for the packages.",
        "NuGet.CommandLine not installed. The package was not found with the source(s) listed.",
        " Source(s): '//repository/Microsoft/BoxStarterSetup'",
        " NOTE: When you specify explicit sources, it overrides default sources.",
        "If the package version is a prerelease and you didn't specify `--pre`,",
        " the package may not be found.",
        "Please see https://chocolatey.org/docs/troubleshooting for more ",
        " assistance.",
        "",
        "Chocolatey installed 0/1 packages. 1 packages failed.",
        " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).",
        "",
        "Failures",
        " - NuGet.CommandLine - NuGet.CommandLine not installed. The package was not found with the source(s) listed.",
        " Source(s): '//repository/Microsoft/BoxStarterSetup'",
        " NOTE: When you specify explicit sources, it overrides default sources.",
        "If the package version is a prerelease and you didn't specify `--pre`,",
        " the package may not be found.",
        "Please see https://chocolatey.org/docs/troubleshooting for more ",
        " assistance."
    ],
    "stderr_lines": [],
    "_ansible_no_log": false
}`
that

**Comment by mwtrigg** [comment]
You will be unable to use a source in one task, when in the immediately preceding task you set its state to "absent"

**Comment by andrescolodrero** [comment]
@mwtrigg  sorry, i copy the code for the incorrect code repo branch (where i remove the config to avoid error)

so the correct source code when the job failed is:

`- name: Add artifactory netshare internal source
win_chocolatey_source:
name: BoxStarter
state: present
priority: 10
source: //repository/Microsoft/BoxStarterSetup

**Comment by andrescolodrero** [comment]
running this from windows works:
choco install Nuget.CommandLine -source='//repository/Microsoft/BoxStarterSetup' (single quoted)

**Comment by mwtrigg** [comment]
How do you authenticate to the share?  Are you trying to double-hop?  Do you have delegation in your ansible config or playbook?

If you're using Kerberos, you can try this (at the same level as the task)

vars:
  ansible_winrm_kerberos_delegation: true

Or, since you're double-hopping look into using become: true and the appropriate become_user, method, flags, and optionally password.

**Comment by andrescolodrero** [comment]
Hi, i tested signing with the same user on the windows servers, and worked.
then i added
ansible_winrm_kerberos_delegation: true
and run the playbook.

thanks, thats what a good catch!
