### ISSUE TITLE
Upgrade status unclear?

### ISSUE THREAD

**Issue by beardedfool** [chocolatey/chocolatey-ansible#39]
I think I'm experiencing the path problems on a new install and see you have a fix released but can you clarify the upgrade process to 1.1.0 - Bugfixes & --remove-dependencies support

I have...
```
# /home/andy/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.posix         1.2.0  
ansible.windows       1.4.0  
chocolatey.chocolatey 1.1.0  
```

So do I have the fix or not?

Though I can see this is coming https://github.com/ansible/ansible/issues/65699#issuecomment-772832432

When that is implemented, will an update here be instant, or is there still a delay being approved by ansible-galaxy?

**Comment by beardedfool** [comment]
It's possible I have a different problem/ am an idiot as rebooting the machine doesn't solve it which I think it should if related to https://github.com/chocolatey/chocolatey-ansible/issues/34


`- name: install chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present`


`[WARNING]: Chocolatey was missing from this system, so it was installed during this task run.
fatal: [happy]: FAILED! => {"changed": true, "msg": "Failed to find choco.exe, make sure it is added to the PATH or the env var 'ChocolateyInstall' is set", "rc": 0}`

**Comment by vexx32** [comment]
That is quite odd. This module does a few different checks to try to ensure chocolatey is installed properly, and as you say while the PATH issues look similar, they should have been sorted out after a reboot. 

You seem to have v1.1.0 installed, so you should have the fix for that issue, as well. If attempting this on a fresh system still doesn't work, let us know, I suppose? I'll see if I can figure out what's going on in the meantime as well. 🙂

**Comment by beardedfool** [comment]
Thanks, 

please don't waste your time on it if I'm the only report of it, likley that machine. 
I'll be able to test on the fresh installs within 48 hours and will report back

Back to the upgrade process just in case I come across it again though please... should galaxy instantly pull any new releases at present, or is it a manual process?

**Comment by vexx32** [comment]
I'm not 100% clear on that myself to be honest, but I believe it's a manual process to upgrade collections, similar to python's `pip`?

**Comment by beardedfool** [comment]
glad it's not just me ;)

That link I sent earlier seems to suggest it's coming in ansible-base 2.11
though

**Comment by vexx32** [comment]
Closing this off for now, seems like there is a workaround for the time being, and the actual update command is coming soon. Feel free to give me a ping/open a new issue if there are any issues with upgrading this collection specifically. 🙂
