### ISSUE TITLE
Move to GPLv3+ License

### ISSUE THREAD

**Issue by vexx32** [chocolatey/chocolatey-ansible#5]
The original code that was inherited from the Ansible team is licensed as GPL v3+; it makes more sense for us to adopt that license with the code we've added than to try to re-license the entire project as MIT or Apache.

The following folks have contributed under the MIT license & will need to OK the change for the new additions to be moved to GPL v3+ and match with the original licensing. See [here](https://www.gnu.org/licenses/gpl-3.0.txt) for the full GPLv3 license.

- [x] @adilio 
- [x] @vexx32 
- [x] @steviecoaster 

I will submit a PR to update the license and licensing headers on all the project files.

**Comment by steviecoaster** [comment]
Definitely something we should do. I agree with the change.

**Comment by vexx32** [comment]
I also approve the change. 👍

**Comment by pauby** [comment]
Has a discussion been had with @ferventcoder ?

**Comment by vexx32** [comment]
Over email & Zoom, yep. I'll forward you the email chain. 🙂

**Comment by pauby** [comment]
No need to forward it on. He was missing from the list of approvers, hence my question.

**Comment by adilio** [comment]
I also approve the change. 👍

**Comment by ferventcoder** [comment]
@pauby yep, all good from my end. I didn't need to approve it here as I am not one of the committers.
