### ISSUE TITLE
Build: Test collection against multiple Ansible versions

### ISSUE THREAD

**Issue by vexx32** [chocolatey/chocolatey-ansible#57]
Per Jordan's comment below:

> (...) You should be testing against ansible-base/core and not ansible (as packaged in PyPI. The ansible package is ansible-base/core at a particular version with this collection already bundled. What you want to ensure you are testing is the engine itself which is packaged as these 3 names
>
> ansible - at 2.9
> ansible-base - at 2.10
> ansible-core - at 2.11+

We should be able to reuse the Azure VM and run 3 different Pipelines runners against it sequentially.

**Comment by jborean93** [comment]
Just an FYI you should be testing against `ansible-base/core` and not `ansible` (as packaged in PyPI. The `ansible` package is `ansible-base/core` at a particular version with this collection already bundled. What you want to ensure you are testing is the engine itself which is packaged as these 3 names

* `ansible` - at 2.9
* `ansible-base` - at 2.10
* `ansible-core` - at 2.11+
