### ISSUE TITLE
 Win_chocolatey ansible module not create folders in 'lib' folder for all package versions of a side by side package

### ISSUE THREAD

**Issue by alastairbondie** [chocolatey/chocolatey-ansible#63]
**Summary of issue**

If you install 2 or more versions of the same package via win_chocolatey ansible module, it does not always create all the files needed at  "C:\ProgramData\chocolatey\lib" for all the versions, so that when you uninstall one via win_chocolatey module it cannot find the files to uninstall.

'At C:\ProgramData\chocolatey\lib' win_chocolatey should create all 3 folders for say a package called zbrush if you are installing 3 versions side by side

Example versions to be installed via ansible win_chocolatey module

![image](https://user-images.githubusercontent.com/97687047/149359669-f1a3ac04-71ae-4c6f-99a4-730b12c35e9f.png)

This is what was created in C:\ProgramData\chocolatey\lib and will cause uninstall problems
![image](https://user-images.githubusercontent.com/97687047/149369514-dade1e19-bc92-4be3-9b27-c737928dbb5f.png)

This is what should have been created instead, which would uninstall ok
![image](https://user-images.githubusercontent.com/97687047/149361461-61faf403-7f48-45fa-8cc6-340dd9fd21bb.png)

Win_chocolatey module uninstalled zbrush 2021.7.1-f01 but not the other 2 versions in add/remove programs

Symptoms
When you use ansible module win_chocolatey to try to uninstall zbrush with "state: absent" it will only uninstall zbrush.2021.71.1-f01 and think that the other 2 are already uninstalled and leave them in add/remove programs still installed.
As you can see from this ansible example run, it returned a  'green' status of the uninstall of 2 of the versions, as it thought that they were uninstalled already.

Here is ansible win_chocolatey trying to uninstall all 3 versions, 2021.7.1-f01 is uninstalled but the other 2 versions remain in add/remove programs as they did not have any files/folders created in 'At C:\ProgramData\chocolatey\lib' when installed.
TASK [chocolatey_packages : Print list of packages to install (or uninstall)] *****************************************************************************************
ok: [blahhostname.blah.com] =>
  chocolatey_packages_stack:
  - allow_multiple: true
    name: zbrush
    state: absent
    version: 2019.1.1-f01
  - allow_multiple: true
    name: zbrush
    state: absent
    version: 2020.1-f01
  - allow_multiple: true
    name: zbrush
    state: absent
    version: 2021.7.1-f01
Thursday 13 January 2022  11:37:00 +0000 (0:00:00.023)       0:00:10.145 ******
 
TASK [chocolatey_packages : Configure Profile Packages] ***************************************************************************************************************
included: /net/homes/blahusername/git/repo_name/roles/chocolatey_packages/tasks/packages.yml for blahhostname.blah.com => (item={'allow_multiple': True, 'name': 'zbrush', 'state': 'absent', 'version': '2019.1.1-f01'})
included: /net/homes/blahusername/git/repo_name/roles/chocolatey_packages/tasks/packages.yml for blahhostname.blah.com => (item={'allow_multiple': True, 'name': 'zbrush', 'state': 'absent', 'version': '2020.1-f01'})
included: /net/homes/blahusername/git/repo_name/roles/chocolatey_packages/tasks/packages.yml for blahhostname.blah.com => (item={'allow_multiple': True, 'name': 'zbrush', 'state': 'absent', 'version': '2021.7.1-f01'})
Thursday 13 January 2022  11:37:00 +0000 (0:00:00.063)       0:00:10.209 ******
 
TASK [chocolatey_packages : Configure Package "zbrush" - State "absent" - Version "2019.1.1-f01" - Force = No - Allow_multiple "True"] ********************************
ok: [blahhostname.blah.com]
Thursday 13 January 2022  11:37:10 +0000 (0:00:06.104)       0:00:20.517 ******
 
 
TASK [chocolatey_packages : Configure Package "zbrush" - State "absent" - Version "2020.1-f01" - Force = No - Allow_multiple "True"] **********************************
ok: [blahhostname.blah.com]
Thursday 13 January 2022  11:37:18 +0000 (0:00:05.909)       0:00:28.048 ******
 
TASK [chocolatey_packages : Configure Package "zbrush" - State "absent" - Version "2021.7.1-f01" - Force = No - Allow_multiple "True"] ********************************
changed: [blahhostname.blah.com]
 
PLAY [all] ************************************************************************************************************************************************************
Thursday 13 January 2022  11:37:47 +0000 (0:00:27.280)       0:00:57.170 ******

Note: Anything saying 'blah' or 'repo_name' is to disguise internal information

**Root cause**
If you install 2 or more versions of the same package via win_chocolatey ansible module, it does not always create all the files needed at  "C:\ProgramData\chocolatey\lib" for all the versions. This seems to be a bug in that module

Additional files and information
=========================
Ansible install run

[zbrush ansible bug install.txt](https://github.com/chocolatey/chocolatey-ansible/files/7864566/zbrush.ansible.bug.install.txt)

Chocolatey logs
[chocolatey.log](https://github.com/chocolatey/chocolatey-ansible/files/7864563/chocolatey.log)
[choco.summary.log](https://github.com/chocolatey/chocolatey-ansible/files/7864564/choco.summary.log)

**Comment by alastairbondie** [comment]
Here is the edit install ansible run

[zbrush ansible bug install.txt](https://github.com/chocolatey/chocolatey-ansible/files/7864406/zbrush.ansible.bug.install.txt)

**Comment by alastairbondie** [comment]
Uploaded chocolatey logs
[choco.summary.log](https://github.com/chocolatey/chocolatey-ansible/files/7864464/choco.summary.log)
[chocolatey.log](https://github.com/chocolatey/chocolatey-ansible/files/7864466/chocolatey.log)

**Comment by pauby** [comment]
Havre you tried this without ansible in the mix (ie. native Chocolatey)? I suspect this is a `choco` issue with installing multiple versions (which YMMV with) and not `win_chocolatey`?

**Comment by alastairbondie** [comment]
HI Pauby, yes I have and it works fine with choco install/choco uninstall which is why I think it is a bug with win_chocolatey ansible module. I am happy to be wrong but here below is the choco install commands working fine

PS C:\Windows\system32> choco list --pre --allversions | findstr zbrush
zbrush 2021.7.1-f01
zbrush 2020.1-f01
zbrush 2019.1.1-f01
PS C:\Windows\system32>

Installed all 3 versions 1 by 1 similar to this
`<html>
<body>


PS C:\Windows\system32> choco install zbrush --pre --version 2020.1-f01 -y -mChocolatey v0.10.15 BusinessInstalling the following packages:zbrushBy installing you accept licenses for the packages.zbrush v2020.1-f01zbrush package files install completed. Performing other installation steps.Installing ZBrush_2020.1_FL_Installer.exe...ZBrush_2020.1_FL_Installer.exe has been installed.\\dfs.ldn.framestore.com\net\wdmspackages\binaries\zbrush\2020.1\license_ZBrush4_1_1seat.lic1 File(s) copied\\dfs.ldn.framestore.com\net\wdmspackages\binaries\zbrush\2020.1\FloatingLicenseDLL.dll1 File(s) copied zbrush may be able to be automatically uninstalled. The install of zbrush was successful. Software installed to 'C:\Program Files/Pixologic/ZBrush 2020.1 FL'Chocolatey installed 1/1 packages. See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
--



</body>
</html>`

In add remove programs it looks like this
![image](https://user-images.githubusercontent.com/97687047/149561138-399d18f7-7c7c-44c1-80f6-23e68057d760.png)

In C:\ProgramData\chocolatey\lib' the packages were correctly created

![image](https://user-images.githubusercontent.com/97687047/149561205-f117d481-5f91-41f2-b7bc-3fef7e47c02d.png)

So I could uninstall all versions ok

`
PS C:\Windows\system32> choco uninstall zbrush --pre --allversions
Chocolatey v0.10.15 Business
Uninstalling the following packages:
zbrush
zbrush v2019.1.1-f01
Uninstalling zbrush...
0
zbrush has been uninstalled.
 Running auto uninstaller...
 Skipping auto uninstaller - 'ZBrush 2019.1.1 FL' appears to have been uninstalled already by other means.
WARNING: No registry key found based on 'ZBrush 2019.1.1 FL*'
WARNING: zbrush has already been uninstalled by other means.
 Running auto uninstaller...
 Skipping auto uninstaller - 'ZBrush 2019.1.1 FL' appears to have been uninstalled already by other means.
 zbrush has been successfully uninstalled.
zbrush v2020.1-f01
Uninstalling zbrush...
0
zbrush has been uninstalled.
 Running auto uninstaller...
 Skipping auto uninstaller - 'ZBrush 2020.1 FL' appears to have been uninstalled already by other means.
WARNING: No registry key found based on 'ZBrush 2020.1 FL*'
WARNING: zbrush has already been uninstalled by other means.
 Running auto uninstaller...
 Skipping auto uninstaller - 'ZBrush 2020.1 FL' appears to have been uninstalled already by other means.
 zbrush has been successfully uninstalled.
zbrush v2021.7.1-f01
Uninstalling zbrush...
0
zbrush has been uninstalled.
 Running auto uninstaller...
 Skipping auto uninstaller - 'ZBrush 2021 FL' appears to have been uninstalled already by other means.
 Auto uninstaller has successfully uninstalled zbrush or detected previous uninstall.
 Auto uninstaller has successfully uninstalled zbrush or detected previous uninstall.
WARNING: No registry key found based on 'ZBrush 2021 FL*'
WARNING: zbrush has already been uninstalled by other means.
 Running auto uninstaller...
 Skipping auto uninstaller - 'ZBrush 2021 FL' appears to have been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17' appears to have
been uninstalled already by other means.
 Skipping auto uninstaller - 'Microsoft Visual C++ 2010 x64 Redistributable - 10.0.30319' appears to have been
uninstalled already by other means.
 zbrush has been successfully uninstalled.
Chocolatey uninstalled 3/3 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Windows\system32>
`

**Comment by vexx32** [comment]
I think I see the issue. These are the command lines that are being sent during install by the ansible collection:

```
"C:\ProgramData\chocolatey\choco.exe" install zbrush --fail-on-unfound --yes --no-progress --limit-output --allow-multiple --prerelease --source \\dfs_servername\sharename\wdmspackages\nupkgs --timeout 2700 --version 2019.1.1-f01
```

```
"C:\ProgramData\chocolatey\choco.exe" upgrade zbrush --fail-on-unfound --yes --no-progress --limit-output --allow-multiple --prerelease --source \\dfs_servername\sharename\wdmspackages\nupkgs --timeout 2700 --version 2020.1-f01
```

```
"C:\ProgramData\chocolatey\choco.exe" upgrade zbrush --fail-on-unfound --yes --no-progress --limit-output --allow-multiple --prerelease --source \\dfs_servername\sharename\wdmspackages\nupkgs --timeout 2700 --version 2021.7.1-f01
```

This seems to be root of the problem -- on the later installs, we seem to be passing the command as `upgrade` and not `install`. I've seen something similar in the past, but the issue there was the ansible task being specified with `state: latest` and not `state: present`.

Can you confirm the resulting Ansible playbook you're using on your end and the `state` value being used? When doing side by side package installs, you need to be using `state: present` and not `state: latest`.

**Comment by alastairbondie** [comment]
Hi vexx32, thanks for this, that was extremely helpful. I was using state: latest by default in ansible, I changed it to use state: present and it all works correctly now. I will close this ticket

**Comment by alastairbondie** [comment]
Thanks to vexx32 and Pauby
