### ISSUE TITLE
Vagrant environment does not load ansible.windows modules correctly

### ISSUE THREAD

**Issue by vexx32** [chocolatey/chocolatey-ansible#71]
### What You Are Seeing?

Specifically in the Vagrant environment, running the tests seems to cause a few errors about `ansible.windows` modules like `win_command` and `win_file` to show up. These don't appear to be problematic in CI, so it may be something with the Vagrant environment specifically or the boxes we're using.

Errors noted include:

```
couldn't resolve module/action 'win_command'. This often indicates a misspelling, missing collection, or incorrect module path

couldn't resolve module/action 'win_file'. This often indicates a misspelling, missing collection, or incorrect module path
```

I tested both with and without fully qualified module syntax (`ansible.windows.<name>`) and both cases failed, which leads me to believe there's something else going on, and it only shows up in Vagrant environment for some reason.

### What is Expected?

Vagrant should run all the tests, the same as the CI runner.

### How Did You Get This To Happen? (Steps to Reproduce)

Run the `build/Invoke-CollectionTests.ps1` script.

**Comment by vexx32** [comment]
Reopening as this seems to still be an issue, though still unsure why this is happening.

**Comment by voskampm** [comment]
Hi: Have you tried to increase the amount of memory for the Vagrant VM? The VM created by Vagrant only has 1 GB of memory. The VM used in Azure CI is a 'Standard_DS2_v2' which has 7 GB of Ram.  I also use Vagrant to run the test of the Chocolatey collection and I experienced random compiler errors on a 4GB Windows 2016 VM. Those errors disappeared when I increased the memory to 8 GB and I managed to run all tests successfully. 

My errors:
`fatal: [win10]: FAILED! => {"changed": false, "msg": "internal error: failed to run exec_wrapper action module_powershell_wrapper: Failed to compile C# code: \r\nerror CS0583: Internal Compiler Error (0xc0000005 at address 00007FF60B64AE7F): likely culprit is 'BIND'.\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(1017,21) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(1002,17) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(1001,22) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(997,22) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(995,17) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(993,13) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(992,13) : error CS0585: Internal Compiler Error: stage 'BIND'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(986,22) : error CS0584: Internal Compiler Error: stage 'BIND' symbol 'Ansible.Basic.AnsibleModule.CheckUnsupportedArguments(System.Collections.IDictionary, System.Collections.Generic.List<string>)'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(986,22) : error CS0584: Internal Compiler Error: stage 'COMPILE' symbol 'Ansible.Basic.AnsibleModule.CheckUnsupportedArguments(System.Collections.IDictionary, System.Collections.Generic.List<string>)'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(33,18) : error CS0584: Internal Compiler Error: stage 'COMPILE' symbol 'Ansible.Basic.AnsibleModule'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(31,11) : error CS0584: Internal Compiler Error: stage 'COMPILE' symbol 'Ansible.Basic'\r\nc:\\Users\\vagrant\\AppData\\Local\\Temp\\x1shvnal.0.cs(31,11) : error CS0584: Internal Compiler Error: stage 'COMPILE' symbol 'Ansible'\r\nerror CS0584: Internal Compiler Error: stage 'COMPILE' symbol '<global namespace>'\r\nerror CS0586: Internal Compiler Error: stage 'COMPILE'\r\nerror CS0587: Internal Compiler Error: stage 'COMPILE'\r\nerror CS0587: Internal Compiler Error: stage 'EMIT'\r\nerror CS0587: Internal Compiler Error: stage 'BEGIN'"}
`

**Comment by vexx32** [comment]
That's a good point, thanks! I'll give that a go and update the vagrant file in the repo if that turns out to solve it fully. 🙂

**Comment by voskampm** [comment]
I was too quick. The random errors are back. Very strange problem....
