### ISSUE TITLE
1.3.0 issue with installing packages

### ISSUE THREAD

**Issue by dawidjttf** [chocolatey/chocolatey-ansible#91]
### What You Are Seeing?

> Chocolatey package '7zip' is already installed with version(s) '' but was expecting '21.7'. Either change the expected version, set state=latest or state=upgrade, set allow_multiple=yes, or set force=yes to continue",

### What is Expected?

7zip package gets installed

### How Did You Get This To Happen? (Steps to Reproduce)

> 
     wks_packages:
    - name: 7zip
      version: 21.7
      allow_multiple: no

    - name: Install Software packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        source: ChocolateyInternal
        state: present
        allow_multiple: "{{ item.allow_multiple }}"
      loop: "{{ wks_packages }}"

This started happening with the latest 1.3.0 version, it works fine in 1.2.0

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19044.0
* Windows PowerShell version (Run: `$PSVersionTable`):

> PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

* Chocolatey version (Run `choco --version`): 1.1.0

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

> {
  "changed": false,
  "invocation": {
    "module_args": {
      "ignore_checksums": false,
      "source_username": null,
      "architecture": "default",
      "ignore_dependencies": false,
      "remove_dependencies": false,
      "allow_prerelease": false,
      "choco_args": null,
      "allow_multiple": false,
      "source_password": null,
      "source": "ChocolateyInternal",
      "version": "21.7",
      "state": "present",
      "override_args": false,
      "proxy_username": null,
      "pinned": null,
      "allow_empty_checksums": false,
      "force": false,
      "skip_scripts": false,
      "name": [
        "7zip"
      ],
      "timeout": 2700,
      "proxy_password": null,
      "install_args": null,
      "proxy_url": null,
      "package_params": null,
      "validate_certs": true,
      "bootstrap_script": null
    }
  },
  "rc": 0,
  "command": "",
  "msg": "Chocolatey package '7zip' is already installed with version(s) '' but was expecting '21.7'. Either change the expected version, set state=latest or state=upgrade, set allow_multiple=yes, or set force=yes to continue",
  "_ansible_no_log": false,
  "item": {
    "name": "7zip",
    "version": 21.7,
    "allow_multiple": false
  },
  "ansible_loop_var": "item",
  "_ansible_item_label": {
    "name": "7zip",
    "version": 21.7,
    "allow_multiple": false
  }
}

</p>

</details>

**Comment by vexx32** [comment]
Thanks for reporting the issue! Are you able to retrieve the chocolatey log file from the target node(s) that are showing this issue as well?

**Comment by jonahbull** [comment]
I ran into this issue as well recently and I think I've figured out what's going on.

Here are the system details just in case they're helpful:
* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.17763.0
* Windows PowerShell version (Run: `$PSVersionTable`):
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
* Chocolatey version (Run `choco --version`): 0.10.15

Before https://github.com/chocolatey/chocolatey-ansible/pull/72 was merged, the logic for figuring out what to do when a version was explicitly specified and force wasn't set looked like this: https://github.com/chocolatey/chocolatey-ansible/blob/92effc9b6be0399599b8b20a18568a9269aebcbc/chocolatey/plugins/modules/win_chocolatey.ps1#L802-L807
If `$package` isn't currently installed then the `$package_info.$package` lookup returns `$null`.
Here's a simple example of how that worked when `$package` wasn't installed:
```powershell
$package_info = @{'vault' = $null}
$package = 'vault'
$package_versions = [System.Collections.ArrayList]$package_info.$package
Write-Output "package_versions.Count: $($package_versions.Count)"
package_versions.Count: 0
```
As expected, `$package_versions.Count` is 0.

After https://github.com/chocolatey/chocolatey-ansible/pull/72 was merged, that same logic changed subtly: 
https://github.com/chocolatey/chocolatey-ansible/blob/42a297f96a3a66ad6a68359acf5621fdb2f74aa8/chocolatey/plugins/modules/win_chocolatey.ps1#L190-L196
Again, if `$package` isn't currently installed then the `$package_info.$package` lookup returns `$null`.
Here's a simplified example of the current code when `$package` isn't installed:
```powershell
$packageInfo = @{'vault' = $null}
$package = 'vault'
$packageVersions = @($packageInfo.$package)
Write-Output "packageVersions.Count: $($packageVersions.Count)"
packageVersions.Count: 1
```
Unexpectedly, `$packageVersions.Count` is 1!
That leads us into the next set of conditionals and the error that we're seeing.

So it seems like `$package_versions = [System.Collections.ArrayList]$package_info.$package` and `$packageVersions = @($packageInfo.$package)` produce different results when the package info lookup returns `$null`.
The first one produces `$null`, and the second produces an array with a single item, which is `$null`.
I'm not a powershell expert so I'm afraid I don't know why those two very similar variable declarations have different results.

To work around the issue I added a conditional that creates an empty array when the `$packageInfo.$package` lookup is `$null`:
``` powershell
    # If version is specified and installed version does not match or not
    # allow_multiple, throw error. Ignore this if force is set.
    if ($state -eq "present" -and $null -ne $version -and -not $force) {
        foreach ($package in $name) {

            if ($packageInfo.$package -eq $null) {
                $packageVersions = @()
            } else {
                $packageVersions = @($packageInfo.$package)
            }

            if ($packageVersions.Count -gt 0) {
```
I'll look at turning that into a PR when I've got some time next week.

**Comment by vexx32** [comment]
That's a really good investigation, thanks for running through all that! That makes sense to me. I think you could also possibly sort it out by filtering out null entries explicitly, something like:

```ps1
$packageVersions = @($packageInfo.$package | Where-Object { $_ })
```

**Comment by jonahbull** [comment]
Thanks for the suggestion, seems much more idiomatic than my attempt :smile:  I incorporated it into https://github.com/chocolatey/chocolatey-ansible/pull/93.
