### ISSUE TITLE
Module fails to execute if powershell version is older than version 5

### ISSUE THREAD

**Issue by clavecin** [chocolatey/chocolatey-ansible#92]
The module is failing to execute on PowerShell 4 or older because the code uses an operator (`::new()`) that is only available on PowerShell 5 or newer.

Attempting to execute the module on PowerShell 4 causes the following error:
    ```Method invocation failed because [System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=...]]] does not contain a method named 'new'.\r\nAt line:177 char:5\r\n+ $missingPackages = [System.Collections.Generic.List[string]]::new()```

https://github.com/chocolatey/chocolatey-ansible/blob/b7e6e962d486035104686a1e1e23ec8c2e1137af/chocolatey/plugins/modules/win_chocolatey.ps1#L177

**Comment by vexx32** [comment]
Ah, good catch. We should use `[System.Collections.Generic.List[string]]@()` instead for compatibility. Thanks for the report!

**Comment by opoplawski** [comment]
Any chance of a 1.4.0 release soon?  Thanks.

**Comment by vexx32** [comment]
Should be fairly soon, yep!
