### ISSUE TITLE
win_chocolatey - Deprecate side-by-side installs

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-ansible#94]
## Is Your Feature Request Related To A Problem? Please describe.

Side-by-side installs are planned to be deprecated in a future (potentially version 2.0) of Chocolatey CLI. We need to ensure we properly deprecate this in the collection.

Note that _before_ this is deprecated, we will have documentation describing the options available to continue to have similar functionality.

## Describe The Solution. Why is it needed?

Side-by-side installs are being deprecated.

## Additional Context.

_Before_ this is deprecated, we will have documentation describing the options available to continue to have similar functionality.

## Related Issues

- Issue https://github.com/chocolatey/choco/issues/2787

**Comment by pauby** [comment]
[Documentation was added](https://docs.chocolatey.org/en-us/create/create-packages#naming-packages-to-allow-for-side-by-side-installation).

**Comment by vexx32** [comment]
Noting here that we will also need to pull our minimum Ansible-core version to 2.10 as a minimum, as deprecating module params is not available in 2.9.

[2.9 through 2.11 of ansible-core are considered EOL by Ansible](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-changelogs), so we shouldn't have any issues dropping them from our CI testing rotation.
